# Generated by Django 4.1.5 on 2023-03-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('Teaxher', 'Teacher'), ('Student', 'Student')], default='2', max_length=10),
        ),
    ]
